name: Build and Push to ECR

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 클론
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. AWS 인증 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # 3. ECR 로그인
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 481665107235.dkr.ecr.ap-northeast-2.amazonaws.com

    # 4. Docker 이미지 빌드 및 태깅 (user-registration-service)
    - name: Build and Tag Docker Image - User Registration Service
      run: |
        docker build -t user-registration-service:latest ./backend-root/user-registration-service
        docker tag user-registration-service:latest 481665107235.dkr.ecr.ap-northeast-2.amazonaws.com/user-registration-service:latest

    # 5. Docker 이미지 빌드 및 태깅 (user-login-service)
    - name: Build and Tag Docker Image - User Login Service
      run: |
        docker build -t user-login-service:latest ./backend-root/user-login-service
        docker tag user-login-service:latest 481665107235.dkr.ecr.ap-northeast-2.amazonaws.com/user-login-service:latest

    # 6. Docker 이미지 ECR에 푸시 (user-registration-service)
    - name: Push Docker Image to ECR - User Registration Service
      run: docker push 481665107235.dkr.ecr.ap-northeast-2.amazonaws.com/user-registration-service:latest

    # 7. Docker 이미지 ECR에 푸시 (user-login-service)
    - name: Push Docker Image to ECR - User Login Service
      run: docker push 481665107235.dkr.ecr.ap-northeast-2.amazonaws.com/user-login-service:latest

